all:
	(cd event_providers && $(MAKE)) >/dev/null
	(cd menus && $(MAKE)) >/dev/null
	(cd speedtest_overlay && $(MAKE)) >/dev/null
	(cd popup_keys && $(MAKE)) >/dev/null
	(cd wifi_panel && $(MAKE)) >/dev/null
	(cd agents_panel && $(MAKE)) >/dev/null
	(cd volume_panel && $(MAKE)) >/dev/null
